import turtle
wn = turtle.Screen()
wn.bgcolor("light green")
wn.title("Turtle")
t=turtle.Turtle()
t.setheading(30)
t.pensize(10)
t.forward(300)
t.right(125)
t.forward(100)
t.right(125)
t.forward(100)
wn.exitonclick()
